config/routes.rb
Rails.application.routes.draw do
  root "pdf#index"
  post '', to: "pdf#index"
  get 'prawn', to: 'pdf#prawn'
  get 'wicked', to: 'pdf#wicked'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pdf_controller.rb
class PdfController < ApplicationController
  def index
    @text = params[:text] || 'বাম  চোখ'
  end

  def prawn
    pdf = PdfGenerator::Prawn.new(params[:text])
    send_data pdf.render, filename: 'test.pdf', type: 'application/pdf', disposition: 'inline'
  end

  def wicked
    pdf = PdfGenerator::Wicked.new(params[:text])
    send_data pdf.render, filename: 'test.pdf', type: 'application/pdf', disposition: 'inline'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pdf_helper.rb
module PdfHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/pdf.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <%= wicked_pdf_stylesheet_link_tag "pdf" -%>
    <style>
      body { font-family: 'Khmer'; }
    </style>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/pdf/index.html.erb
<%= form_with url: root_path, method: :post do |form| %>
  <%= form.text_area :text, value: @text, style: 'width: 600px; height: 300px;' %>
  <%= form.submit 'Generate' %>
<% end %>

<% if @text %>
  <h3>Prawn</h3>
  <iframe src="<%= prawn_path(text: @text) %>" style="width: 600px; height: 300px;"></iframe>
  <h3>Wicked PDF</h3>
  <iframe src="<%= wicked_path(text: @text) %>" style="width: 600px; height: 300px;"></iframe>
<% end %>

app/views/pdf/wicked.html.erb
<p><%= text %></p>